version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: edureka
      MYSQL_DATABASE: docker
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8888:80"
    stdin_open: true
    tty: true
