version: '3'
services:
  php_mysql:
    build: mysql/.
    image: php_mysql
    environment:
      MYSQL_ROOT_PASSWORD: edureka
      MYSQL_DATABASE: docker
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-bridge-network
  php-web:
    build: web/.
    image: php_web
    depends_on:
      - php_mysql
    ports:
      - "8888:80"
    networks:
      - my-bridge-network
volumes:
  my-datavolume:
networks:
  my-bridge-network:
    driver: bridge
