version: '3'
services:
  php-mysql:
    build: mysql/.
    image: php_mysql
    environment:
      MYSQL_ROOT_PASSWORD: edureka
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-bridge-network
  php_web:
    build: web/.
    image: php_web
    ports:
      - "8888:80"
    networks:
      - my-bridge-network
volumes:
  my-datavolume:
networks:
  my-bridge-network:
    driver: bridge
