version: '3.7'
services:
  php_mysql:
    image: pbeniwal/php_mysql
    environment:
      MYSQL_ROOT_PASSWORD: edureka
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-overlay-network
  php_web:
    image: pbeniwal/php_web:v1
    ports:
      - "8888:80"
    networks:
      - my-overlay-network
volumes:
  my-datavolume:
networks:
  my-overlay-network:
    driver: overlay
